[comment {--- Standard trailer for all manpages in this module --}]
[section Authors]
[uri https://github.com/andreas-kupries/ {Andreas Kupries}] (Tcl Binding),
[uri https://github.com/msteveb/ {Steve Bennett}] (extended linenoise C library),
[uri https://github.com/antirez/ {Salvatore Sanfilippo}] (Antirez, original linenoise C library).

[section {Bugs, Ideas, Feedback}]

This document, and the package it describes, will undoubtedly contain
bugs and other problems.

Please report them at the
[uri https://github.com/andreas-kupries/tcl-linenoise/issues {Issues tracker}].

Ideas for enhancements you may have for either package, application,
and/or the documentation are also very welcome and should be reported
at the [uri https://github.com/andreas-kupries/tcl-linenoise/issues {Issues tracker}] as well.
