[comment {--- Standard trailer for all manpages in this module --}]
[section Authors]
Andreas Kupries, Antirez (C level linenoise)

[section {Bugs, Ideas, Feedback}]

This document, and the package it describes, will undoubtedly contain
bugs and other problems.

Please report them at [uri https://github.com/andreas-kupries/tcl-linenoise/issues].

Ideas for enhancements you may have for either package, application,
and/or the documentation are also very welcome and should be reported
at [uri https://github.com/andreas-kupries/tcl-linenoise/issues] as well.
