
[subsection CriTcl]

To build the linenoise binding the tool [syscmd critcl] is required.

[para] The build system accept it either as an application found in
the PATH, or as a Tcl package available to the [syscmd tclsh] used to
run their build & installation processes.

[para] We [emph must] have version 3.1 or higher.

[para] Its github repository can be found at
[uri http://andreas-kupries.github.com/critcl].

[para] At the above url is also an explanation on how to build and
install CriTcl, including a list of its dependencies.

[para] Its instructions will not be repeated here. If there are
problems with their directions please file a bug against the critcl
project, and not tcl-linenoise.
