
[subsection Kettle]

To build Linenoise the build support package [package kettle] is
required.

[para] This package must be available to the [syscmd tclsh] used to
run Linenoise's build & installation process, and the [syscmd tclsh]
used to run scripts requiring Linenoise.

[para] Kettle's fossil repository can be found at
[uri http://chiselapp.com/user/andreas_kupries/repository/Kettle/home].

[para] The relevant repository branch is [emph trunk].

[para] Kettle has a build and installation guide much like this one for
Linenoise, which can be found at the above site and explains how to
retrieve its sources and build the package, which dependencies are
required, etc. The direct link to this guide is
[uri http://chiselapp.com/user/andreas_kupries/repository/Kettle/doc/tip/embedded/www/doc/files/kettle_installer.html]

[para] Its instructions will not be repeated here. If there are
problems with their directions please file a bug against the kettle
project, and not Linenoise.
